server:
  port: 8080
spring:
  application:
    name: cloud-consumer-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:7001/eureka


