server:
  port: 8002
spring:
  application:
    name: cloud-pay-service
  datasource:
    username: root
    password: PokePet123456!
    url: jdbc:mysql://47.101.47.149:3306/spring-cloud-test?charaterEncoding=utf8&autoReconnect=true&serverTimezone=UTC&useUnicode=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      asyncInit: true
      validationQuery: select 1
      filters: stat



mybatis:
  type-aliases-package: com.rocketscience.entity
  mapper-locations: classpath:mapper/*.xml


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: pay8002
    prefer-ip-address: true #访问路径可以显示ip地址